Repository nathanielvarona/pritunl-api-go, pull requests merged in 2024-04, with the labels that each got.

#1 API Client Authentication and Server Status
  .editorconfig
  .github/labels.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
  .gitignore
  README.md
  go.mod
  go.sum
  pritunl.go
  status.go
Labels: type: feature

#2 Examples for Status
  .editorconfig
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
  README.md
  example/status.go
Labels: type: improvement

#3 Fix Release Drafter
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
Labels: type: automation

#5 Get Users by Organization and Specific User by Organization
  .golintci.yaml
  examples/status-get.go
  examples/user-get.go
  status.go
  user.go
Labels: type: feature

#6 Usage and Features Status
  README.md
Labels: type: documentation

#7 Create User is Added
  client.go
  examples/status-get.go
  examples/user-create.go
  examples/user-get.go
  pritunl.go
  user.go
Labels: type: feature

#9 Delete User is Added
  README.md
  examples/.gitignore
  examples/status-get.go
  examples/user-delete.go
  status.go
  user.go
Labels: type: feature

#10 Dry User Features
  README.md
  examples/status-get.go
  examples/user-delete.go
  examples/user-get.go
  examples/user-update.go
  user.go
Labels: type: improvement

#11 JSON Unmarshal Helper for DRY User Features
  README.md
  examples/status-get.go
  examples/user-delete.go
  examples/user-update.go
  user.go
Labels: type: improvement

#12 Organization Get is Added
  README.md
  common.go
  examples/.gitignore
  examples/organization-get.go
  examples/user-create.go
  examples/user-delete.go
  examples/user-get.go
  examples/user-update.go
  organization.go
  user.go
Labels: type: feature

#13 Organization Create is Added
  README.md
  examples/.gitignore
  examples/organization-create.go
  organization.go
Labels: type: feature

#14 Organization Update is Added
  README.md
  examples/.gitignore
  examples/organization-update.go
  organization.go
Labels: type: feature

#18 Server Create is Added
  README.md
  examples/.gitignore
  examples/server-create.go
  examples/server-get.go
  server.go
Labels: type: feature

#19 Server Update is Added
  README.md
  examples/.gitignore
  examples/server-update.go
  server.go
Labels: type: feature

#20 Server Delete is Added
  README.md
  examples/.gitignore
  examples/server-create.go
  examples/server-delete.go
  examples/server-update.go
  server.go
Labels: type: feature

#21 Order of Precedence for API Credentials
  client.go
  examples/status-get.go
  server.go
Labels: type: improvement

#22 Update Feature Simple Roadmap Table
  README.md
Labels: type: documentation

#23 Server Route Get is Added
  README.md
  examples/.gitignore
  examples/serverroute-get.go
  serverroute.go
Labels: type: feature

#24 Server Route Create is Added
  README.md
  _examples/.gitignore
  _examples/key-get.go
  _examples/organization-create.go
  _examples/organization-delete.go
  _examples/organization-get.go
  _examples/organization-update.go
  _examples/server-create.go
  _examples/server-delete.go
  _examples/server-get.go
  _examples/server-update.go
  _examples/serverroute-create.go
  _examples/serverroute-get.go
  _examples/status-get.go
  _examples/user-create.go
  _examples/user-delete.go
  _examples/user-get.go
  _examples/user-update.go
  serverroute.go
Labels: type: feature

#25 Server Route Update is Added
  README.md
  _examples/.gitignore
  _examples/serverroute-update.go
  serverroute.go
Labels: type: feature

#26 Server Route Delete is Added
  README.md
  _examples/.gitignore
  _examples/serverroute-delete.go
  serverroute.go
Labels: type: feature

#27 Server Organization Attach is Added
  README.md
  _examples/.gitignore
  _examples/serverorg-attach.go
  server.go
  serverorg.go
Labels: type: feature

#29 Server Host Attach is Added
  README.md
  _examples/.gitignore
  _examples/serverhost-attach.go
  serverhost.go
Labels: type: feature

#30 Server Host Detach is Added
  README.md
  _examples/.gitignore
  _examples/serverhost-detach.go
  serverhost.go
  serverorg.go
Labels: type: feature

#31 Examples Cleanup
  README.md
  _examples/key-get.go
  _examples/organization-delete.go
  _examples/organization-get.go
  _examples/organization-update.go
  _examples/server-delete.go
  _examples/server-get.go
  _examples/server-update.go
  _examples/serverorg-attach.go
  _examples/serverorg-detach.go
  _examples/serverroute-create.go
  _examples/serverroute-delete.go
  _examples/serverroute-get.go
  _examples/serverroute-update.go
  _examples/user-create.go
  _examples/user-delete.go
  _examples/user-get.go
  _examples/user-update.go
Labels: type: improvement

#32 DRY and Clear Package Documentation
  .editorconfig
  .gitignore
  README.md
  _examples/key-get.go
  _examples/organization-create.go
  _examples/organization-delete.go
  _examples/organization-get.go
  _examples/organization-update.go
  _examples/server-create.go
  _examples/server-delete.go
  _examples/server-get.go
  _examples/server-update.go
  _examples/serverhost-attach.go
  _examples/serverhost-detach.go
  _examples/serverorg-attach.go
  _examples/serverorg-detach.go
  _examples/serverroute-create.go
  _examples/serverroute-delete.go
  _examples/serverroute-get.go
  _examples/serverroute-update.go
  _examples/status-get.go
  _examples/user-create.go
  _examples/user-delete.go
  _examples/user-get.go
  _examples/user-update.go
  client.go
  common.go
  go.mod
  key.go
  organization.go
  server.go
  serverhost.go
  serverorg.go
  serverroute.go
  status.go
  user.go
Labels: type: improvement

#33 Remove Empty Byte with Nil for Get Method Payload
  README.md
  _examples/status-get.go
  _examples/user-create.go
  _examples/user-update.go
  key.go
  organization.go
  server.go
  serverhost.go
  serverorg.go
  serverroute.go
  status.go
  user.go
Labels: type: improvement

#34 Insure Examples are Working
  _examples/organization-delete.go
  _examples/server-delete.go
  _examples/serverorg-detach.go
  _examples/serverroute-delete.go
  _examples/user-delete.go
  _examples/user-get.go
  _examples/user-update.go
  server.go
Labels: type: improvement

#35 DRY Unmarshal Handler for Organization
  README.md
  organization.go
Labels: type: improvement

#36 Sonarqube Static Code Analysis
  .gitignore
  .sonarcloud.properties
  README.md
Labels: type: automation

#37 Future Enhancement Links
  README.md
Labels: type: documentation

#38 Public the User Substructs
  user.go
Labels: type: improvement

#39 Development and Contributing Guidelines
  README.md
Labels: type: documentation

#41 Development and Contribution to Go Workspace Workflow
  .editorconfig
  .gitignore
  README.md
Labels: type: documentation

#40 Add ServerStop and ServerStart methods
  _examples/.gitignore
  _examples/server-start.go
  _examples/server-stop.go
  server.go
Labels: type: improvement

#43 Rebasing and Squashing Commits for Contribution
  README.md
Labels: type: documentation

#44 Community Standards for Contributing
  CONTRIBUTING.md
Labels: type: documentation
